name = "Imaginocean"
uuid = "12c4ca38-4e4f-41dd-8fa8-8127a85ce97a"
license = "MIT"
authors = ["Climate Modeling Alliance and contributors"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"

[compat]
Makie = "0.19"
Oceananigans = "0.81 - 0.90, 0.91"
